"""refactor planet table

Revision ID: 4735642d287f
Revises: 206da339d6cf
Create Date: 2024-11-05 13:45:16.543235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4735642d287f'
down_revision = '206da339d6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('moons_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('distance_from_sun',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('distance_from_sun',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('moons_num',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
